import Navbar from "../../components/Navbar";
import "./globals.css";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Himanshu",
  description: "Generated by create next app",
   icons: {
    icon : "/icon.png"
   }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
          <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
