import React from 'react';

const PrivacyPolicyPage = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12 bg-white text-gray-900 leading-relaxed">
      <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-2">Last updated: August 24, 2025</p>
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>

      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
      
      <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-semibold mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>

      <ul className="list-disc list-inside mb-6 space-y-2">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party...</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Himanshudm.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website...</li>
        <li><strong>Country</strong> refers to: Delhi, India</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company...</li>
        <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself...</li>
        <li><strong>Website</strong> refers to Himanshudm, accessible from{' '}
          <a href="https://www.himanshudm.pro/" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">
            https://www.himanshudm.pro/
          </a>
        </li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      {/* Add more sections similarly as needed */}
      
      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc list-inside mt-2">
        <li>
          By visiting this page on our website:{' '}
          <a href="https://www.himanshudm.pro/contact" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">
            https://www.himanshudm.pro/contact
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicyPage;
